// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltntgfeebirpixtlhwrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bnRnZmVlYmlycGl4dGxod3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzk4NDMsImV4cCI6MjA3MDg1NTg0M30.9TYguwi_wTYVUccGJ4itpuIY0tK2SXDojnKlAn95PEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});